---
title: "linear model with predictions"
author: "Jennifer Alvarez"
date: "10/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## introdution 
this is the linear model with prediction problem.
predict strength scores using data from the following website.


```{r}
dataF <- read.csv(file="http://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt", sep= "" ,header=TRUE)
```

```{r include=FALSE}
require(tidyverse)
require(tigerstats)
require (rgl)
require(knitr)
require(ggplot)
```

### PLOT SCATTERPLOT

```{r}
plot(SIMS~ARM,data=dataF)
```

```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=ARM))
basicNN + geom_point() + geom_smooth(method=lm)
```



## Now add the model fit to our plot

```{r}
model.1 <- lm(SIMS~ARM,data=dataF)
summary.lm(model.1)
New=data.frame(GRIP=94,ARM=88)
predict.lm(model.1,New,interval="prediction")
```

in model 1 we have an adjusted r square value of 0.467



## Compare the two models. Note ADJR r2 larger residual SE is smaller in model.2



## conclusion 






